version: "3.9"

services:
  notes:
    build:
      context: .
    volumes:
      - ./notes:/opt/notes
    ports:
      - "80:8080"
    command: >
      sh -c "cd /opt/notes/ && go run ."
    depends_on:
      - db

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: "notes-user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notes"
