version: "3.9"

services:
  notes:
    build:
      context: .
    volumes:
      - ./<APP>:/opt/<APP>
    ports:
      - "80:8080"
    command: >
      sh -c "cd /opt/<APP>/ && go run ."
    depends_on:
      - db

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: "notes-user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notes"
